pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                docker build -t foobargem/foo:test
            }
        }
        stage('Deploy') {
            steps {
                docker images
            }
        }
    }
}
